services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: ${ACR_LOGIN_SERVER}/${DAGSTER_IMAGE_NAME}:${DAGSTER_IMAGE_TAG}

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: ${ACR_LOGIN_SERVER}/${DASHBOARD_IMAGE_NAME}:${DASHBOARD_IMAGE_TAG}